language: rust

sudo: required

services:
    - docker

before_install:
    - docker pull influxdb
    - docker run -d -p 8086:8086 --name influxdb influxdb
    - docker run -d -p 9086:8086 --name authed_influxdb -e INFLUXDB_HTTP_AUTH_ENABLED=true -e INFLUXDB_ADMIN_USER=admin -e INFLUXDB_ADMIN_PASSWORD=password -e INFLUXDB_USER=nopriv_user -e INFLUXDB_USER_PASSWORD=password influxdb
    - docker ps

branches:
    only:
        - master

cache:
    directories:
        - /home/travis/.cargo

before_cache:
    - rm -rf /home/travis/.cargo/registry

env:
os:
    - linux
rust:
    - stable
    - beta
    - nightly

matrix:
    fast_finish: true
    allow_failures:
    include:
        - rust: stable
          env: NAME='linting'
          before_script:
              - rustup component add rustfmt-preview
              - rustup component add clippy-preview
          script:
              - cargo fmt --all -- --check
              - cargo clippy --all-targets --all-features -- -D warnings

        - rust: stable
          env: NAME='readme-check'
          before_script:
              - bash auxiliary/update_cargo-readme.sh
          script:
              - bash auxiliary/check_readme_consistency.sh

script: |
    export RUST_BACKTRACE=1 &&
    cargo build &&
    cargo test &&
    cargo doc --no-deps
