language: rust

sudo: required

before_install:
    - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.7.6_amd64.deb
    - sudo dpkg -i influxdb_1.7.6_amd64.deb
    - sudo influxd > $HOME/influx.log 2>&1 &

branches:
    only:
        - master

env:
    - RUSTFLAGS='-C link-dead-code' TEST_DIR=.

rust:
    - stable
    - nightly

matrix:
    allow_failures:
        - rust: nightly

script:
    - cd $TEST_DIR && cargo build && cargo test

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev

after_success: |
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
    sudo make install && cd ../.. &&
    kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/influxdb-*
