# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = ["influxdb", "influxdb_derive"]

<<<<<<< HEAD
[patch.crates-io]
influxdb = { path = "./influxdb" }
influxdb_derive = { path = "./influxdb_derive" }
=======
[dependencies]
reqwest = "0.9.17"
futures = "0.1.27"
tokio = "0.1.20"
failure = "0.1.5"
serde = { version = "1.0.92", optional = true }
serde_json = { version = "1.0", optional = true }
chrono = { version = "0.4.9", optional = true }

[features]
use-serde = ["serde", "serde_json"]
chrono_timestamps = ["chrono"]
default = ["use-serde"]
>>>>>>> main/master
