# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "influxdb"
version = "0.0.5"
authors = ["Gero Gerke <11deutron11@gmail.com>"]
edition = "2018"
description = "InfluxDB Driver for Rust"
keywords = ["influxdb", "database", "influx"]
license = "MIT"
readme = "README.md"
include = ["src/**/*", "tests/**/*", "Cargo.toml", "LICENSE"]
repository = "https://github.com/Empty2k12/influxdb-rust"

[badges]
travis-ci = { repository = "Empty2k12/influxdb-rust", branch = "master" }

[dependencies]
failure = "0.1.5"
futures = "0.1.27"
influxdb_derive = { version = "0.0.1", optional = true }
reqwest = "0.9.17"
serde = { version = "1.0.92", optional = true }
serde_json = { version = "1.0", optional = true }
tokio = "0.1.20"
chrono = { version = "0.4.9", features = ["serde"] } 

[features]
default = []
use-serde = ["serde", "serde_json"]
derive = ["influxdb_derive"]
